### PR TITLE
Have kept values in arrays merged with generated values

### LINKED ISSUE #3: Adding a keep comment in a list kills the list
If you have an attribute that is generated (like `compiler_flags`) and you add a `# keep` comment to one of the entries, running gazelle on it will kill the entire list:

```
compiler_flags = [
   "-DSOME_VAR=1", # keep
   # Generated flags here
  ...
]
```

will convert to

```
compiler_flags = [
   "-DSOME_VAR=1", # keep
]
```

Expected behavior would be to keep the generated flags along with the entries marked with the `# keep` comment.

### PR DESCRIPTION
**Pull request by facundominguez**
Closes #3

### CODE REVIEW

**Comment by facundominguez** [comment]
@symbiont-rahul-muttineni, please, let me know if this PR doesn't fix it for you.

**Review by aherrmann — APPROVED** [review]
Thank you!

It would be good to have a regression test for this as well. Perhaps some golden tests?

**Comment by facundominguez** [comment]
I thought about including in the build files some binary rule that matches a generated rule. Then we can see that it succeeds to build after running gazelle, while having some essential dependency declared with `# keep`.

I'll try it later.

**Comment by facundominguez** [comment]
I pushed the test now. I checked that it fails without the fix here.

**Comment by aherrmann** [comment]
> I thought about including in the build files some binary rule that matches a generated rule. Then we can see that it succeeds to build after running gazelle, while having some essential dependency declared with `# keep`.
> 
> I'll try it later.

Thank you!

**Pull request merged**
